name: Build
on:
  push:
    branches:
    - main
jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        bash ci.sh do_deps
        sudo apt-get install -y icecc
        sudo sed -i 's/^ICECC_SCHEDULER_HOST=""$/ICECC_SCHEDULER_HOST="sch01-tc-build"/' /etc/icecc/icecc.conf
        echo 'ICECC_DEBUG="-vvv"' | sudo tee -a /etc/icecc/icecc.conf
        sudo systemctl daemon-reload
        sudo systemctl restart iceccd
    - uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{secrets.TS_OAUTH_CLIENT_ID}}
        oauth-secret: ${{secrets.TS_OAUTH_SECRET}}
        hostname: usr01-tc-build
        tags: tag:ci
        args: --ssh
    - name: Build LLVM
      run: ICECC_DEBUG=debug PATH=/usr/lib/icecc/bin:$PATH JOBS=128 bash ci.sh do_llvm -D CMAKE_C_COMPILER_LAUNCHER=icecc CMAKE_CXX_COMPILER_LAUNCHER=icecc LLVM_PARALLEL_COMPILE_JOBS=128 LLVM_PARALLEL_LINK_JOBS=128
    - name: Build binutils
      run: ICECC_DEBUG=debug PATH=/usr/lib/icecc/bin:$PATH JOBS=128 bash ci.sh do_binutils -D CMAKE_C_COMPILER_LAUNCHER=icecc CMAKE_CXX_COMPILER_LAUNCHER=icecc LLVM_PARALLEL_COMPILE_JOBS=128 LLVM_PARALLEL_LINK_JOBS=128
    - name: Build kernel
      run: ICECC_DEBUG=debug PATH=/usr/lib/icecc/bin:$PATH JOBS=128 bash ci.sh do_kernel
    - name: Fix up build
      run: bash ci.sh do_fixup
    - name: Make dist
      run: bash ci.sh do_dist
    - uses: actions/upload-artifact@v3
      with:
        path: tc-dist.tar.zst

  scheduler:
    runs-on: ubuntu-latest
    steps:
    - name: Install and start icecream scheduler
      run: |
        sudo apt-get install -y icecc
        sudo sed -i 's/^ICECC_SCHEDULER_HOST=""$/ICECC_SCHEDULER_HOST="sch01-tc-build"/' /etc/icecc/icecc.conf
        echo 'ICECC_DEBUG="-vvv"' | sudo tee -a /etc/icecc/icecc.conf
        sudo systemctl daemon-reload
        sudo systemctl restart icecc-scheduler
    - uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{secrets.TS_OAUTH_CLIENT_ID}}
        oauth-secret: ${{secrets.TS_OAUTH_SECRET}}
        hostname: sch01-tc-build
        tags: tag:ci
        args: --ssh
    - name: Stay with user builder...
      run: |
        while ! ping -c 1 usr01-tc-build 2>/dev/null; do sleep 1; done
        while ping -c 1 usr01-tc-build >/dev/null; do sleep 30; done

  builders:
    strategy:
      matrix:
        host: [bld01, bld02, bld03, bld04, bld05, bld06, bld07, bld08, bld09, bld10, bld11, bld12, bld13, bld14, bld15, bld16, bld17, bld18, bld19, bld20, bld21, bld22, bld23, bld24, bld25, bld26, bld27, bld28, bld29, bld30, bld31, bld32]
    runs-on: ubuntu-latest
    steps:
    - name: Install and start icecream daemon
      run: |
        sudo apt-get install -y icecc
        sudo sed -i 's/^ICECC_SCHEDULER_HOST=""$/ICECC_SCHEDULER_HOST="sch01-tc-build"/' /etc/icecc/icecc.conf
        echo 'ICECC_DEBUG="-vvv"' | sudo tee -a /etc/icecc/icecc.conf
        sudo systemctl daemon-reload
        sudo systemctl restart iceccd
    - name: Get hostname
      run: echo "HOSTNAME=${{matrix.host}}-tc-build" >> $GITHUB_ENV
    - uses: tailscale/github-action@v2
      with:
        oauth-client-id: ${{secrets.TS_OAUTH_CLIENT_ID}}
        oauth-secret: ${{secrets.TS_OAUTH_SECRET}}
        hostname: ${{env.HOSTNAME}}
        tags: tag:ci
        args: --ssh
    - name: Stay with scheduler...
      run: |
        while ! ping -c 1 sch01-tc-build 2>/dev/null; do sleep 1; done
        while ping -c 1 sch01-tc-build >/dev/null; do sleep 30; done
