name: Build distribution
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install dependencies
      run: bash ci.sh deps
    - name: Build LLVM
      run: bash ci.sh llvm
    - name: Build binutils
      run: bash ci.sh binutils
    - name: Build kernel
      run: bash ci.sh kernel
    - name: Fix up build
      run: bash ci.sh fixup
    - name: Make dist
      run: bash ci.sh dist
    - uses: actions/upload-artifact@main
      with:
        path: tc-build-install.tar.xz
